apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  # these labels are deployment resources
  labels:
    app: app2
spec:
# modify replicas according to your case
  replicas: 2
  selector:
  # replicaset use these labels to find the pods for creating desired number of replicas
    matchLabels:
     app: app2
  # pod template
  template:
    metadata:
      labels:
        app: app2
       
    spec:   
     containers:
     - name: app2
       image: ayeshacs540/app2:1.0.0
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec: 
  type: LoadBalancer
  selector: #labels arre used as selectors
    app: app2
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 #container port number
---
 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip 
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:869935092837:certificate/73436fc3-0059-4c9d-b837-108611b725b9
    alb.ingress.kubernetes.io/group.name: ayeshacs540
spec:
  ingressClassName: alb
  rules:
  - host: "app2.noor3.online"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app2
            port:
              number: 80
